# Generated by Django 5.2.17 on 2026-08-25 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customermembership'),
        ('permissions', '0001_initial'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_roles', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['customer', 'is_active'], name='roles_role_custome_99ad16_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('customer', 'slug'), name='unique_customer_role_slug'),
        ),
    ]
