# Generated by Django 5.2.17 on 2026-08-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_remove_legacy_superadmin_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('name',)},
        ),
    ]
