# Generated by Django 5.2.17 on 2026-09-02 13:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_simplify_company_name'),
        ('customers', '0005_remove_customer_roles_delete_customerrole'),
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('country_code', models.CharField(max_length=2)),
                ('vat', models.CharField(blank=True, max_length=100)),
                ('standard_shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('authorization_required', 'Authorization Required'), ('expired', 'Expired'), ('error', 'Error'), ('disconnected', 'Disconnected')], db_index=True, default='pending', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='customers.customer')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='platforms.platform')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CdiscountChannelCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller_id', models.CharField(max_length=255)),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cdiscount_credentials', to='channels.channel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AmazonChannelCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller_id', models.CharField(max_length=255)),
                ('refresh_token', models.TextField()),
                ('access_token', models.TextField(blank=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_token_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_credentials', to='channels.channel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EbayChannelCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ebay_user_id', models.CharField(blank=True, max_length=255)),
                ('refresh_token', models.TextField()),
                ('access_token', models.TextField(blank=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_token_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_credentials', to='channels.channel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('country_code', models.CharField(max_length=2)),
                ('currency_code', models.CharField(blank=True, max_length=3)),
                ('external_marketplace_id', models.CharField(blank=True, max_length=150)),
                ('region', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplaces', to='platforms.platform')),
            ],
            options={
                'ordering': ('platform__name', 'country_code', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ChannelMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('orders_enabled', models.BooleanField(default=True)),
                ('listings_enabled', models.BooleanField(default=True)),
                ('inventory_enabled', models.BooleanField(default=True)),
                ('prices_enabled', models.BooleanField(default=True)),
                ('last_orders_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_listing_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_inventory_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_price_sync_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_marketplaces', to='channels.channel')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_marketplaces', to='channels.marketplace')),
            ],
            options={
                'ordering': ('marketplace__country_code',),
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='marketplaces',
            field=models.ManyToManyField(related_name='channels', through='channels.ChannelMarketplace', to='channels.marketplace'),
        ),
        migrations.CreateModel(
            name='OttoChannelCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otto_credentials', to='channels.channel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WooCommerceChannelCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_url', models.URLField(max_length=500)),
                ('consumer_key', models.TextField()),
                ('consumer_secret', models.TextField()),
                ('verify_ssl', models.BooleanField(default=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='woocommerce_credentials', to='channels.channel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelAuthorizationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_states', to='channels.channel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_authorization_states', to='customers.customer')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_authorization_states', to='platforms.platform')),
            ],
            options={
                'indexes': [models.Index(fields=['platform', 'expires_at', 'used_at'], name='channel_oauth_state_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='channelmarketplace',
            constraint=models.UniqueConstraint(fields=('channel', 'marketplace'), name='unique_marketplace_per_channel'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['customer', 'platform'], name='channel_customer_platform_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['customer', 'is_active'], name='channel_customer_active_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['customer', 'company'], name='channel_customer_company_idx'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(fields=('customer', 'name'), name='unique_channel_name_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.CheckConstraint(condition=models.Q(('standard_shipping_cost__gte', 0)), name='channel_shipping_cost_nonnegative'),
        ),
    ]
