# Generated by Django 5.2.17 on 2026-09-08 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('customers', '0005_remove_customer_roles_delete_customerrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAmazonSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lwa_client_id', models.TextField()),
                ('lwa_client_secret', models.TextField()),
                ('spapi_application_id', models.TextField()),
                ('authorization_url', models.URLField(default='https://sellercentral-europe.amazon.com/apps/authorize/consent', max_length=500)),
                ('oauth_callback_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_channel_setting', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerEbaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('redirect_uri', models.TextField()),
                ('authorization_url', models.URLField(default='https://auth.ebay.com/oauth2/authorize', max_length=500)),
                ('oauth_callback_url', models.URLField(max_length=500)),
                ('oauth_scopes', models.TextField(default='https://api.ebay.com/oauth/api_scope')),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_channel_setting', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
