# Generated by Django 5.2.17 on 2026-08-24 15:21

import apps.companies.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_name', models.CharField(max_length=100)),
                ('complete_name', models.CharField(max_length=255)),
                ('street_1', models.CharField(blank=True, max_length=255)),
                ('street_2', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, db_index=True, max_length=30)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('fax', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.FileField(blank=True, null=True, upload_to=apps.companies.models.company_logo_path)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='customers.customer')),
            ],
            options={
                'ordering': ('short_name',),
                'indexes': [models.Index(fields=['customer', 'is_active'], name='companies_c_custome_51fe18_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('customer', 'short_name'), name='unique_active_company_short_name_per_customer')],
            },
        ),
    ]
