# Generated by Django 5.2.17 on 2026-08-14 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("roles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customerrole",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customerrole",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_roles",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="customerrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_roles",
                to="roles.role",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="roles",
            field=models.ManyToManyField(
                related_name="customers",
                through="customers.CustomerRole",
                to="roles.role",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerrole",
            constraint=models.UniqueConstraint(
                fields=("customer", "role"), name="unique_customer_role"
            ),
        ),
    ]
