# Generated by Django 5.2.17 on 2026-08-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_backfill_owner_memberships'),
        ('roles', '0003_remove_legacy_superadmin_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='roles',
        ),
        migrations.DeleteModel(
            name='CustomerRole',
        ),
    ]
