# Generated by Django 5.2.17 on 2026-09-21 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_product_languages'),
        ('customers', '0005_remove_customer_roles_delete_customerrole'),
    ]

    operations = [
    ]
