# Generated by Django 5.2.17 on 2026-08-25 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_simplify_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('street1', models.CharField(blank=True, max_length=255)),
                ('street2', models.CharField(blank=True, max_length=255)),
                ('plz', models.CharField(blank=True, db_index=True, max_length=30)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('fax', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='companies.company')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['company', 'name'], name='warehouses__company_d983b6_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='unique_warehouse_name_per_company')],
            },
        ),
    ]
