# Generated by Django 5.2.17 on 2026-09-21 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_wooproductimport_productstock"),
        ("warehouses", "0003_warehouse_company"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productstock",
            name="unique_product_warehouse_stock",
        ),
        migrations.AddField(
            model_name="productstock",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warehouse_stock",
                to="products.productvariant",
            ),
        ),
        migrations.AddConstraint(
            model_name="productstock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", True)),
                fields=("product", "warehouse"),
                name="unique_product_warehouse_stock",
            ),
        ),
        migrations.AddConstraint(
            model_name="productstock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", False)),
                fields=("variant", "warehouse"),
                name="unique_variant_warehouse_stock",
            ),
        ),
    ]
